In [1]:
import numpy as np
import pandas as pd
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

In [2]:
path = open('data.csv')
data = np.loadtxt(path, delimiter=",")


In [3]:
data

array([[ 0.78051  , -0.063669 ,  1.       ],
       [ 0.28774  ,  0.29139  ,  1.       ],
       [ 0.40714  ,  0.17878  ,  1.       ],
       [ 0.2923   ,  0.4217   ,  1.       ],
       [ 0.50922  ,  0.35256  ,  1.       ],
       [ 0.27785  ,  0.10802  ,  1.       ],
       [ 0.27527  ,  0.33223  ,  1.       ],
       [ 0.43999  ,  0.31245  ,  1.       ],
       [ 0.33557  ,  0.42984  ,  0.       ],
       [ 0.23448  ,  0.24986  ,  1.       ],
       [ 0.0084492,  0.13658  ,  1.       ],
       [ 0.12419  ,  0.33595  ,  1.       ],
       [ 0.25644  ,  0.42624  ,  1.       ],
       [ 0.4591   ,  0.40426  ,  1.       ],
       [ 0.44547  ,  0.45117  ,  1.       ],
       [ 0.42218  ,  0.20118  ,  0.       ],
       [ 0.49563  ,  0.21445  ,  1.       ],
       [ 0.30848  ,  0.24306  ,  1.       ],
       [ 0.39707  ,  0.44438  ,  1.       ],
       [ 0.32945  ,  0.39217  ,  1.       ],
       [ 0.40739  ,  0.40271  ,  1.       ],
       [ 0.3106   ,  0.50702  ,  1.       ],
       [ 0

In [4]:
data.shape

(100, 3)

In [5]:

X = np.delete(data, 2, 1)
y = np.delete(data, 0, 1)
y = np.delete(y, 0, 1)

In [6]:
y

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],

In [7]:
X

array([[ 0.78051  , -0.063669 ],
       [ 0.28774  ,  0.29139  ],
       [ 0.40714  ,  0.17878  ],
       [ 0.2923   ,  0.4217   ],
       [ 0.50922  ,  0.35256  ],
       [ 0.27785  ,  0.10802  ],
       [ 0.27527  ,  0.33223  ],
       [ 0.43999  ,  0.31245  ],
       [ 0.33557  ,  0.42984  ],
       [ 0.23448  ,  0.24986  ],
       [ 0.0084492,  0.13658  ],
       [ 0.12419  ,  0.33595  ],
       [ 0.25644  ,  0.42624  ],
       [ 0.4591   ,  0.40426  ],
       [ 0.44547  ,  0.45117  ],
       [ 0.42218  ,  0.20118  ],
       [ 0.49563  ,  0.21445  ],
       [ 0.30848  ,  0.24306  ],
       [ 0.39707  ,  0.44438  ],
       [ 0.32945  ,  0.39217  ],
       [ 0.40739  ,  0.40271  ],
       [ 0.3106   ,  0.50702  ],
       [ 0.49638  ,  0.45384  ],
       [ 0.10073  ,  0.32053  ],
       [ 0.69907  ,  0.37307  ],
       [ 0.29767  ,  0.69648  ],
       [ 0.15099  ,  0.57341  ],
       [ 0.16427  ,  0.27759  ],
       [ 0.33259  ,  0.055964 ],
       [ 0.53741  ,  0.28637  ],
       [ 0

In [8]:
# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.05):

    for i in range(len(X)):
        y_test = prediction(X[i],W,b)
        if y[i] - y_test ==1:
            print('increase weights-----------')
            W[0] =+ X[i][0]*learn_rate
            W[1] =+ X[i][1]*learn_rate
            b =+ learn_rate
            print('Output ' + str(y_test))
            print('actual output ' + str(y[i]))
            print('1st input ' + str(X[i][0]))
            print('2nd input ' + str(X[i][1]))
            print('1st input weight ' + str(W[0]))
            print('2st input weight' + str(W[1]))
            print('bias ' + str(b))
            print('Final calculated weight & bias ' + str(W), str(b))
        elif y[i] - y_test == -1:
            print('decrese weights------------')
            W[0] =- X[i][0]*learn_rate
            W[1] =- X[i][1]*learn_rate
            b =- learn_rate
            print('Output ' + str(y_test))
            print('actual output ' + str(y[i]))
            print('1st input ' + str(X[i][0]))
            print('2nd input ' + str(X[i][1]))
            print('1st input weight ' + str(W[0]))
            print('2st input weight' + str(W[1]))
            print('bias ' + str(b))
            print('Final calculated weight & bias ' + str(W), str(b))
    return W, b
    

In [9]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0

In [10]:
def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

In [11]:
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.05, num_epochs = 500):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W1, b1 = perceptronStep(X, y, W, b, learn_rate)
        print('------------')
        print(W1, b1)
        print('------------ epoc ' + str(i))
        boundary_lines.append((W1, b1))
        
    return boundary_lines


In [12]:
d = trainPerceptronAlgorithm(X, y)

decrese weights------------
Output 1
actual output [0.]
1st input 0.33557
2nd input 0.42984
1st input weight [-0.0167785]
2st input weight[-0.021492]
bias -0.05
Final calculated weight & bias [[-0.0167785]
 [-0.021492 ]] -0.05
increase weights-----------
Output 0
actual output [1.]
1st input 0.23448
2nd input 0.24986
1st input weight [0.011724]
2st input weight[0.012493]
bias 0.05
Final calculated weight & bias [[0.011724]
 [0.012493]] 0.05
decrese weights------------
Output 1
actual output [0.]
1st input 0.42218
2nd input 0.20118
1st input weight [-0.021109]
2st input weight[-0.010059]
bias -0.05
Final calculated weight & bias [[-0.021109]
 [-0.010059]] -0.05
increase weights-----------
Output 0
actual output [1.]
1st input 0.49563
2nd input 0.21445
1st input weight [0.0247815]
2st input weight[0.0107225]
bias 0.05
Final calculated weight & bias [[0.0247815]
 [0.0107225]] 0.05
decrese weights------------
Output 1
actual output [0.]
1st input 0.25476
2nd input 0.34596
1st input weight 